development:
  #:address: smtp.live.com
  :address: mail.tritonls.ca
  :port: 25
  :Domain: tritonls.ca
  :authentication: plain
  :user_name: info@tritonls.ca
  :password: tr1t0n
  :enable_starttls_auto: true 
  :openssl_verify_mode: 'none'

production:
  :address: mail.tritonls.ca
  :port: 25
  :Domain: tritonls.ca
  :authentication: plain
  :user_name: info@tritonls.ca
  :password: tr1t0n
  :enable_starttls_auto: true 
  :openssl_verify_mode: 'none' 